# Generated by Django 5.0.3 on 2024-03-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_placeinfomodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeinfomodel',
            name='image',
            field=models.ImageField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
